import React from 'react'

const About = () => {
  return (<>
    <h1 style={{textAlign:'center'}}>About</h1>
    <div>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatem expedita, aut asperiores tempora repellendus voluptas magnam esse earum, soluta laborum neque quo incidunt obcaecati quidem? Natus soluta enim perspiciatis ducimus, repellat veritatis magnam consequuntur porro asperiores minus reiciendis deserunt culpa reprehenderit temporibus nobis labore ut obcaecati. Animi eligendi similique sit? Esse, quia. Commodi saepe, culpa quia, aliquam adipisci aut pariatur rerum neque quo, enim vitae ea veritatis odio dolores quis perspiciatis soluta a et molestias aliquid iste? Dolore vero sapiente libero laboriosam quidem enim ex consequuntur asperiores aliquam architecto, dolorum ducimus? Libero nostrum esse facere id excepturi incidunt omnis possimus ex quisquam totam reiciendis quibusdam illum veniam, quaerat accusantium sequi blanditiis deserunt cum neque iusto eaque provident quo velit! Distinctio, voluptatum. Libero dignissimos reprehenderit quibusdam tenetur earum rerum, necessitatibus suscipit aut magnam! Quis eveniet impedit nulla iusto consequuntur vel nemo inventore voluptatum maxime delectus maiores esse, nesciunt in nisi illo sit autem sed ullam ex voluptatem pariatur consequatur adipisci! Numquam sequi laudantium ab cupiditate laboriosam obcaecati, earum eos ad dolores cumque neque voluptates saepe ducimus voluptatem aperiam nostrum harum corrupti error praesentium rerum rem nemo eaque reiciendis dicta. Dolorem laboriosam recusandae similique. Quasi vero hic praesentium unde amet ratione expedita harum vel illum, exercitationem reiciendis quo repellendus dignissimos nobis libero quod ullam. Corporis pariatur tempora quia, laborum expedita necessitatibus saepe excepturi placeat. Assumenda fuga vel repudiandae nam eum dolorem eius fugit! Quasi nisi unde facilis beatae nam sint magni voluptas a necessitatibus nihil omnis consequatur facere eum assumenda, cumque minus est  ipsa ullam, voluptatum, deleniti fugit? Provident odit natus dolorum consequatur nobis nulla quibusdam et eos non, omnis voluptate eius eum numquam officiis aliquam porro culpa rem modi sequi debitis, assumenda perspiciatis ab vel obcaecati! Distinctio fugit quo quas consequuntur. Excepturi iusto dicta, aliquid non sapiente, dolor iure dolorem accusantium nihil quibusdam eligendi voluptatum, laudantium placeat. Ab corporis molestias delectus aspernatur earum sit? Praesentium, mollitia nulla odio eaque id nemo sunt vero odit dolorem iure. Non quam dolor odit a quidem molestias quis expedita? Earum fuga debitis perspiciatis commodi dolor molestias at esse dolore quod impedit! Facere doloremque modi atque corporis laboriosam distinctio minima pariatur quas veritatis?</div>
    </>
  )
}

export default About